name: Setup Authenticated GitHub Pages Site
on: [workflow_dispatch]
jobs:
  setup-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install jq
        uses: dcarbone/install-jq-action@v2
      - name: Install Auth0 CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/auth0/auth0-cli/main/install.sh | sh -s -- -b .
          sudo cp ./auth0 /usr/local/bin
      - run: |
          cd .github/workflows
          ./setup-site.sh